### ISSUE TITLE
Properly manage unsupported sensors

### ISSUE THREAD

**Issue by Arno500** [mtdcr/homeassistant-aten-pe#4]
Hello!

I think my PDU (_PE6108G_ with firmware `2.4.232`) does not support some of the reports that this integration expects. It makes the integration crash when trying to poll the power related values: indeed, this model does not have per-plug values, only PDU global measurements. It does have however individual plug switch (which seems to works correctly, at least in appearance). I do not currently have the time to fix it, but will probably in a few weeks.

I should probably be able to send some sorts of dumps or anything else required if needed!

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 663, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyasn1/type/univ.py", line 1044, in __float__
    return float(self._value)
           ^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: b'not-support'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1525, in _async_process_registry_update_or_remove
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1000, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1126, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 665, in state
    raise ValueError(
ValueError: Sensor sensor.switch_current has device class 'current', state class 'measurement' unit 'A' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'not-support' (<class 'DisplayString'>)
```

**Comment by mtdcr** [comment]
Hi @Arno500,

can you try to change https://github.com/mtdcr/homeassistant-aten-pe/blob/df184f1a4a906b60c984a7b208c08c0f4b509e29/custom_components/aten_pe/sensor.py#L112-L114 to something like this?
```python
value = await self._device.getAttribute(
    self.entity_description.key, self._outlet
)
if value != b'not-support':
    self._attr_native_value = value
```

**Comment by Arno500** [comment]
It does remove the warning in the logs about this!
The sensors are now just all "Unknown"
