### ISSUE TITLE
After update HA 2024.10.1 the custom integration cannot be loaded

### ISSUE THREAD

**Issue by MrMark79** [mtdcr/homeassistant-aten-pe#5]
Hi mtdcr! First let me tell you that I love your work on this integration. It's a time saver for me :-)
But after the latest update I get this message.
Would look in to it?
WIth high regards,

Logger: homeassistant.setup
Bron: setup.py:334
Eerst voorgekomen: 11:04:52 (1 gebeurtenissen)
Laatst gelogd: 11:04:52

Setup failed for custom integration 'aten_pe': Unable to import component: No module named 'pyasn1.compat.octets'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/aten_pe/__init__.py", line 4, in <module>
    from atenpdu import AtenPE, AtenPEError
  File "/usr/local/lib/python3.12/site-packages/atenpdu/__init__.py", line 30, in <module>
    from pysnmp.hlapi.asyncio import (
  File "/usr/local/lib/python3.12/site-packages/pysnmp/hlapi/asyncio/__init__.py", line 8, in <module>
    from pysnmp.proto.rfc1902 import *
  File "/usr/local/lib/python3.12/site-packages/pysnmp/proto/rfc1902.py", line 8, in <module>
    from pysnmp.proto import rfc1155, error
  File "/usr/local/lib/python3.12/site-packages/pysnmp/proto/rfc1155.py", line 10, in <module>
    from pysnmp.proto import error
  File "/usr/local/lib/python3.12/site-packages/pysnmp/proto/error.py", line 9, in <module>
    from pysnmp import debug
  File "/usr/local/lib/python3.12/site-packages/pysnmp/debug.py", line 8, in <module>
    from pyasn1.compat.octets import octs2ints
ModuleNotFoundError: No module named 'pyasn1.compat.octets'

**Comment by mtdcr** [comment]
Hi @MrMark79,

I'm sorry, but I'm stuck with 2024.9 for now, because the move from pip to uv in 2024.10 broke my docker-based setup. 

Home Assistant moved back from pysnmp-lextudio to pysnmp. This may have caused a conflict. Please try updating the integration to today's release (0.6.3).

**Comment by MrMark79** [comment]
Hi @mtdcr ,
I have updated the integration to 0.6.3. But alas to no avail. The Error message is still the same.
With regards,

**Comment by mtdcr** [comment]
I think you'd need to clean up and/or reinstall pysnmp manually (or start your container with a clean volume where HA installs its downloaded dependencies). The conflict I was referring to happens when multiple Python packages install files in the same location, so they partially overwrite each other. The update to 0.6.3 should help to avoid recreating the conflict.

My setup has a volume mounted to `/.local`, which contains a copy of pysnmp-lextudio that I'd remove. But this changed in HA 2024.10, so I'm afraid I can't offer better help at this point in time.

**Comment by MrMark79** [comment]
I run a VM of Home Assistant. And could not find a way to re-install dependencies. BUT...I rebuild the core via CLI and that did the trick.
Thanks again for the support! 
With regards,

![core-rebuild](https://github.com/user-attachments/assets/51c40c7e-c914-4c7d-a856-97a834e817a8)

**Comment by MrMark79** [comment]
I will close the issue now.
For reference what worked for me:

- update the integration via HACS
- rebuild the ha-core via the cli (command line)
